
development:
  adapter: postgresql
  encoding: unicode
  database: gotta_fit_development
  pool: 5
  username: matthatch
  password:


test: &test
  adapter: postgresql
  encoding: unicode
  database: gotta_fit_test
  pool: 5
  username: matthatch
  password:



cucumber:
  <<: *test